- Create the following functions
    - Define a function that gives no of lines in a text files
    - Define a function that gives no of words in a text file
    - Define a function that gives no of characters in text file
    - Define a function that gives sum of numbers in the text file

In [4]:
# line count in a text file
def lineCount():
    with open('new2.txt', 'r') as data:
        file_data = data.read()
        #return file_data
        lines = file_data.strip().split('\n')
        return "No of lines: "+str(len(lines))
lineCount()

'No of lines: 5'

In [5]:
# word count
def wordCount():
    with open('new2.txt', 'r') as f:
        file_data = f.read().strip()
        lines = file_data.split('\n')
        wc = 0
        for line in lines:
            wc += len(line.split())
        return "No of words: "+str(wc)
wordCount()

'No of words: 28'

In [8]:
def createFile(N):
    with open('new3.txt', 'a') as f:
        for line in range(N):
            f.write('\n'+input('Enter: '))
    with open('new3.txt', 'r') as f:
        return f.read()
createFile(3)

Enter: sdhsj
Enter: sdd
Enter: dsdjh


'anasdjskdasaj\nsdhsj\nsdd\ndsdjh'

In [11]:
def sumNumbers():
    with open('new2.txt', 'r') as f:
        lines = f.read().strip().split('\n')
        s = 0
        for line in lines:
            for word in line.split():
                if(word.isdigit()):
                    s += int(word)
    return s
sumNumbers()

8806

#### Marks Data Analysis
- Define a function that creates a text file in that file N no of students marks should be generated randomly in the range(1,100)
- Define a function to read marks from file list
- Define a function that returns highest mark frequency
- Define a function that returns lowest mark frequency
- Define a function that returns pass percentage(>=35)
- Define a function that returns fail percentage(<35)
- Define a function that returns no students got distinction(>=75)

In [13]:
import random
def marksFile(N):
    with open('marks.txt', 'w') as f:
        for student in range(N):
            m = random.randint(1,101)
            f.write(str(m)+'\n')
    return "Marks file generated successfully..!!!"
#marksFile(60)

In [16]:
def readMarks():
    with open('marks.txt', 'r') as f:
        marks = f.read().strip().split('\n')
        marks = list(map(int, marks))
        return marks
#readMarks()

In [18]:
def highestMarkFreq():
    marks = readMarks()
    v = max(marks)
    return "Highest mark is "+str(v)+" and its frequency is "+str(marks.count(v))
highestMarkFreq()

'Highest mark is 101 and its frequency is 1'

### Numpy - Numerical Python
- For handling array data we will numpy moudle
- It is used for scientific computing
- Numpy arrays are faster than list in python

In [22]:
import numpy as np
# pip install numpy
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))
print(arr.shape)
print(arr.size)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
5


In [26]:
# create 2 dimensional array
arr1 = np.array([[1,2,3],[4,5,6]])
print(arr1)
print(arr1.shape)
print(arr1.size)
print(arr1.ndim)

[[1 2 3]
 [4 5 6]]
(2, 3)
6
2


In [29]:
# create array using arange
arr3 = np.arange(1,10)
print(arr3)

[1 2 3 4 5 6 7 8 9]


In [30]:
print(arr3.reshape(3,3))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [31]:
# creating random data in arrays
np.random.randint(1,10,(3,3))

array([[3, 1, 8],
       [7, 7, 5],
       [4, 8, 1]])

#### Mathematical and Statastical Functions

In [32]:
arr5 = np.random.randint(1,100,(4,4))

In [33]:
print(arr5)

[[48  6 83 84]
 [76 65 83 77]
 [22 94 64  3]
 [70 38 32 71]]


In [34]:
print(arr5.sum())

916


In [35]:
arr5.max()

94

In [36]:
arr5.min()

3

In [37]:
arr5.mean()

57.25

In [39]:
np.median(arr5)

67.5

### Array Slicing

In [41]:
arr6 = np.random.randint(1,10,(3,3))
arr6

array([[3, 4, 8],
       [2, 5, 5],
       [3, 1, 9]])

In [42]:
arr6[0:1,0:3]

array([[3, 4, 8]])

In [43]:
arr6[:,0:1]

array([[3],
       [2],
       [3]])